name: 3 - Caller Workflow
on: [push, workflow_dispatch]
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/3a-reusable-workflow.yml
    with:
      param1: 'Hello, world!'

  call-reusable-workflow2:
    uses: ./.github/workflows/3a-reusable-workflow.yml
    with:
      param1: 'Hello, a second time!'
