name: 7a - Test Released Action
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: dmd0822/hello-world-docker-action@v1
        with:
          who-to-greet: 'GitHub Team'