name: Run Composite Action

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    run-composite-action:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Run custom composite action
            uses: ./.github/my-compostie/