name: Reusable Workflow
on:
  workflow_call:
    inputs:
      param1:
        description: 'A parameter for the workflow'
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input parameter: ${{ inputs.param1 }}"
